import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/HeroSection";
import BackgroundBeam from "@/components/BackgroundBeam";
import Spotlights from "@/components/Spotlight";
import Gradient from "@/components/Gradient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Both background effects in one fixed container */}
        <div className="fixed inset-0 -z-10 bg-transparent">
          <BackgroundBeam />
          <Spotlights />
        </div>
        <Navbar />
        <HeroSection />
        <div className="w-full p-4  mb-8 h-auto flex flex-wrap gap-10 justify-center items-center">
          <Gradient />
          <Gradient />
          <Gradient />
          <Gradient />
          <Gradient />
          <Gradient />
        </div>
        {children}
      </body>
    </html>
  );
}
